//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKaraoke
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKaraoke_DBEntities : DbContext
    {
        public QLKaraoke_DBEntities()
            : base("name=QLKaraoke_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FoodBeverage> FoodBeverages { get; set; }
        public virtual DbSet<FoodService> FoodServices { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<LoginAccount> LoginAccounts { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<roombooking> roombookings { get; set; }
    }
}
