//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKaraoke
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodService
    {
        public int OrderValue { get; set; }
        public string idcard { get; set; }
        public string foodname { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<int> moneyper { get; set; }
        public Nullable<int> value { get; set; }
        public string timecall { get; set; }
        public Nullable<int> @checked { get; set; }
    }
}
