//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKaraoke
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int idinvoice { get; set; }
        public string member { get; set; }
        public Nullable<int> room { get; set; }
        public Nullable<int> foodandbeverage { get; set; }
        public Nullable<int> service { get; set; }
        public Nullable<int> total { get; set; }
        public string daycreate { get; set; }
        public string staff { get; set; }
    }
}
