//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKaraoke
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public string idcard { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public string born { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string daycreate { get; set; }
    }
}
