//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKaraoke
{
    using System;
    using System.Collections.Generic;
    
    public partial class roombooking
    {
        public int orderroom { get; set; }
        public string idroom { get; set; }
        public string idcard { get; set; }
        public string checkin { get; set; }
        public string checkout { get; set; }
        public Nullable<int> paid { get; set; }
        public Nullable<int> @checked { get; set; }
    }
}
