//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKaraoke
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public string idroom { get; set; }
        public string type { get; set; }
        public Nullable<int> people { get; set; }
        public Nullable<int> cash { get; set; }
        public string note { get; set; }
        public string idcard { get; set; }
        public string timestart { get; set; }
        public string timeend { get; set; }
        public Nullable<int> paid { get; set; }
        public Nullable<int> coupon { get; set; }
    }
}
